# Generated by Django 5.0.6 on 2026-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('author', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('quote', 'Quote'), ('tip', 'Fitness Tip'), ('story', 'Success Story'), ('motivation', 'Motivation')], default='quote', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inspiration/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
